GET http://localhost:3000/districts/:districtId/
Authorization: Bearer 




###

POST http://localhost:3000/users/
Content-Type: application/json

{      "username": "christopher_phillips",
  "password": "christy@123",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "christopher_phillips",
  "password": "christy@123"
}